name: Coding Standards and Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: NodeJS cache
        id: node-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-${{ hashFiles( 'package-lock.json' ) }}-${{ hashFiles( '.github/workflows/tests.yml' ) }}

      - name: Install NodeJS dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: JS Coding standards
        run: npm run lint
